### ISSUE TITLE
sitemap.changefreq frontmatter ingnored

### ISSUE THREAD

**Issue by nikmartin** [ExtraHop/metalsmith-sitemap#10]
I have this frontmatter at the top of my blog root page:

```gfm
---
template: blog.hbs
title: Blog
meta-description: MySite Blog
sitemap.changefreq: weekly
private: false
---
```

And my site build chain looks like:

```javascript
  .use(sitemap({
    hostname: 'http://www.mysite.com/'
  }))
```
and it is at the bottom of the chain, just before build. The sitemap output is:

```xml
<url>
        <loc>http://www.mysite.com/pages/about</loc>
        <lastmod>2015-06-23</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>http://www.mysite.com/pages/blog</loc>
        <lastmod>2015-06-24</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
    <url>
        <loc>http://www.mysite.com/pages/contact-us</loc>
        <lastmod>2015-06-23</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>
```

I have also tried setting a default of monthly in the build options, and they all get set to monthly, with no overrides from the frontmatter

**Comment by nikmartin** [comment]
once again, i'm 'doing it wrong'. I took the reference literally for the frontmatter overrides. Dotted notation doesn't go far in YAML

**Comment by boushley** [comment]
This is part of the reason I avoid YAML and use JSON instead.

That said I think something like:
```
---
template: blog.hbs
title: Blog
meta-description: NitroPCR Blog
sitemap:
    changefreq: weekly
private: false
---
```

should work.

If that doesn't work, let me know.
