### ISSUE TITLE
What kind of input does ignoreFiles expect?

### ISSUE THREAD

**Issue by ismay** [ExtraHop/metalsmith-sitemap#11]
It would make sense for it to accept an array of minimatch strings, but that does not seem to be the case. So what does it accept? I couldn't find it in the documentation.

**Comment by avioli** [comment]
The sample on the overview page shows RegExp objects.

This is straight from the source code:
```javascript
    function shouldIgnore(file) {
        return !_.some(options.ignoreFiles, function(ignore) {
            return ignore.test(file);
        });
    }
```
So `ignoreFiles` should be an array of RegExp objects, since `.test()` is a method on [RegExp objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test).

**Comment by ismay** [comment]
I should have known that. Thanks for the reply!

**Comment by ismay** [comment]
By the way, I think it would be a lot simpler to switch to a filter that only process files that match it. Not the other way around, like it currently is. With the current ignoreFiles option I have to use this regex:
```
ignoreFiles: [/.*\.(js|css|jpg|git|md|htaccess|xml|txt)$/],
```
Whereas a `filter` option set to `**/*.html` by default would cover most, if not all, use cases.

**Comment by boushley** [comment]
@avioli Thanks for helping out and showing what needs to be done.

@ismay That's a great addition. You open to making a pull request that adds that as an option? And `includeFiles` option that does the opposite of `ignoreFiles`?

**Comment by ismay** [comment]
I don't know. I think the only way for such a new option to work is if it completely replaced the `ignoreFiles` option. I think it would be much better. With good defaults most people wouldn't even have to change the options.

But that would be a breaking change. I'd be up for submitting a pr, but I haven't had much luck with getting this plugin to work. If you could write some tests for the basic functionality I wouldn't mind taking a look at it.

**Comment by avioli** [comment]
One solution, which would be quite easy, is to add `onlyIncludeFiles ` array as well, negating the return value (fiddle: http://jsfiddle.net/sbyx2edh/), so the code should look like this (not tested other than the fiddle):

```javascript
function plugin(options) {
    //...
    defaultsDeep(options, {
        ignoreFiles: [],
        onlyIncludeFiles: [/./], // will include all files by default
    //...

    function shouldInclude(file) {
        return _.some(options.onlyIncludeFiles, function(ignore) {
            return ignore.test(file);
        });
    }
```

__An alternative__ is to use this RegExp: `/(?=\.(html|htm))/` without modifying the plugin.

It uses Positive lookahead group construct to match without consuming characters, but has an issue that it cannot match strictly end of line, so `/(?=\.(html|htm))$/` is invalid. I believe this shouldn't be a problem, given metalsmith is a static website generator, meaning you are in complete control of the naming conventions - don't name a file with `.html` in its name, or it will be included in the sitemap.

Here is a fiddle, you can play around and see what I mean with the `.html` in the name: https://jsfiddle.net/8fzbpw9f/

**Comment by avioli** [comment]
I just saw the refactor, so sorry if this isn't helpful at all. I believe the plugin should remain as simple as possible, so whatever @boushley decides is fine by me.

**Comment by ismay** [comment]
@avioli np, simplicity is what I'm going for as well. That and a user friendly API.
