### ISSUE TITLE
npm versions not pushed as tags to Github

### ISSUE THREAD

**Issue by jonknapp** [ExtraHop/metalsmith-sitemap#13]
I noticed that the NPM package is at `v1.0.0`, but there is only one tag pushed to Github which is `v0.0.10`. Would you be able to make tags and push those to Github so we can see differences between versions?

**Comment by boushley** [comment]
I've pushed the `1.0.0` tag and the `0.1.0` tag.

**Comment by jonknapp** [comment]
excellent, thanks!
