### ISSUE TITLE
Limit size of xml file(s)

### ISSUE THREAD

**Issue by woodyrew** [ExtraHop/metalsmith-sitemap#17]
Sitemaps files shouldn't exceed 10MB or 50,000 URLs per file. This means you need a sitemap index file. Not sure if this should go into `metalsmith-sitemap` or in `sitemap.js`.

For more infomation, see: http://www.sitemaps.org/faq.html#faq_sitemap_size

**Comment by fantapop** [comment]
sitemap.js handles all creation of actual sitemap.xml file.  In order for us to support that we'd end re- implementing sitemap creation.  I recommend opening this issue with sitemap.  I'll gladly integrate the functionality if they provide a way.

**Comment by woodyrew** [comment]
I believe `sitemap.js` handles this. https://github.com/ekalinin/sitemap.js#example-of-sitemap-index although I think `metalsmith-sitemap` will need to work in a slightly different way maybe?
