### ISSUE TITLE
<url> contains backslashes on Windows systems

### ISSUE THREAD

**Issue by karland** [ExtraHop/metalsmith-sitemap#18]
@boushley would you consider to also change backslashes originating from Windows paths into slashes like [here](https://github.com/superwolff/metalsmith-mapsite/commit/dc43e2885b950c9c0bae8d5debaff84eae7298b2)? Thanks.

**Comment by boushley** [comment]
If you open a PR that seems like a great solution.

I'm no longer a contributor on this package though @njbraun might be able to help you out.

**Comment by karland** [comment]
@boushley Ah thanks. 

I have produced a [PR in my fork](https://github.com/karland/metalsmith-sitemap/commit/c83fda2ecaa746b297e90b020f3dfbd24459762a) without a test case at the moment, which is why I do not want to PR to this repository. The reason is, that `make` currently installs `sitemap 1.6.0` with which the existing tests fail due to `sitemap`improvements. @njbraun Can you help/clarify? Thanks.

**Comment by njbraun** [comment]
@karland repo has been updated to fix unit tests (#19).  If you could submit a new PR, I'd gladly look into merging this change.

Thanks!

**Comment by njbraun** [comment]
Issue should be fixed in #25 and part of release 1.2.0
