### ISSUE TITLE
Current maintainer?

### ISSUE THREAD

**Issue by woodyrew** [ExtraHop/metalsmith-sitemap#21]
What's the best way for issues and PRs to get dealt with? If ExtraHop's not maintaining this, maybe it could be transferred to https://github.com/metalsmith ?

**Comment by nicklasmoeller** [comment]
@ashishsc I saw that you were the latest active member. Could you chip in on this? Holding back on creating a PR, since @woodyrew's wasn't looked at.

**Comment by ashishsc** [comment]
Hi guys, sorry we missed these pull requests, we really appreciate them! We'll review them in our coming sprint next week.

**Comment by ashishsc** [comment]
I replied

**Comment by woodyrew** [comment]
Thanks @ashishsc

**Comment by nicklasmoeller** [comment]
Thank you :)
