### ISSUE TITLE
Is there any way to exclude something from the sitemap?

### ISSUE THREAD

**Issue by AWulkan** [ExtraHop/metalsmith-sitemap#28]
I need to exclude a folder with files in them. Is there any way to do this? The folder is being generated by my pagination plugin.

**Comment by njbraun** [comment]
@AWulkan metalsmith-sitemap can take an optional 'pattern' option that acts as a [minimatch](https://github.com/sindresorhus/multimatch) for files to match.  You should be able to override this with an exclude option (!) for the files you don't want to process.

**Comment by AWulkan** [comment]
Thanks, I should have figured that out myself.
I was able to solve it by doing this:
```
.use(sitemap({
        "hostname": "https://www.example.com",
        "pattern": ["**/*.html","!page/**"],
        "omitIndex": true
    }))
```
