### ISSUE TITLE
`npm install` failing due to bad dependency

### ISSUE THREAD

**Issue by wilsaj** [ExtraHop/metalsmith-sitemap#7]
`to-function@2.0.5` is no longer `npm install`able because of a broken dependency a few levels below that (`to-function -> remove-try-require -> replace-method -> recast`)

**Comment by boushley** [comment]
Ug, semantic versioning can cause so much pain :) Thanks for the PR.

**Comment by boushley** [comment]
New version published that has this change `0.0.10`

**Comment by wilsaj** [comment]
Thanks!
